"""Add phone column to Address

Revision ID: 6541ce5db9bd
Revises: abfc0e2f45b0
Create Date: 2025-08-22 22:02:32.595450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6541ce5db9bd'
down_revision = 'abfc0e2f45b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
