"""Add station_id to User

Revision ID: a14606365866
Revises: 62e9089c40e8
Create Date: 2025-08-23 19:04:17.925461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14606365866'
down_revision = '62e9089c40e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fuel_stations', ['station_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fuel_stations', ['station_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('station_id')

    with op.batch_alter_table('fuel_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('station_id')

    op.drop_table('fuel_stations')
    # ### end Alembic commands ###
